name: flutter_vlc_player
description: A VLC-powered alternative to Flutter's video_player. Supports multiple players on one screen.
version: 7.4.2
homepage: https://github.com/solid-software/flutter_vlc_player/
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

flutter:
  plugin:
    platforms:
      android:
        package: software.solid.fluttervlcplayer
        pluginClass: FlutterVlcPlayerPlugin
      ios:
        pluginClass: FlutterVlcPlayerPlugin

dependencies:
  flutter:
    sdk: flutter

  flutter_vlc_player_platform_interface:
    git: https://github.com/kumsumit/flutter_vlc_player_platform_interface.git
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pigeon: ^0.2.4
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git
  flutter_lints: ^4.0.0